// modulepreload.mjs — tell the browser about the whole module graph at once.
//
// THE PROBLEM. ES modules are discovered by parsing. The browser fetches
// app.js, parses it, and only THEN learns it needs scene.js; it fetches that,
// parses it, and only then learns about world2d.js. Measured on the live site,
// the nineteen modules of this app arrived in five sequential waves and the
// last one landed 3.2 s after the page started — about 2.7 s of it spent
// waiting for round trips that could all have happened at once.
//
// THE FIX. A <link rel="modulepreload"> in the head names a module before any
// parsing has happened, so every fetch starts immediately and in parallel.
// Nothing about the code changes: same modules, same order of execution, same
// bytes. It is purely a hint about what is coming.
//
// This walks the real import graph from js/app.js so the list cannot drift
// from the truth, and test/preload.test.mjs fails if index.html disagrees.

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const ENTRY = 'js/app.js';

/** Static import specifiers in one module. Dynamic import() is deliberately
    skipped: a module behind import() is wanted later, not now. */
function importsOf(rel) {
  const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  // strip block and line comments so a commented-out import is not followed
  const code = src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
  const out = [];
  const re = /(?:^|[\s;}])(?:import|export)\s[^;'"]*?from\s*['"]([^'"]+)['"]/g;
  let m;
  while ((m = re.exec(code))) out.push(m[1]);
  const bare = /(?:^|[\s;}])import\s*['"]([^'"]+)['"]/g;
  while ((m = bare.exec(code))) out.push(m[1]);
  return out.filter((s) => s.startsWith('.'));
}

/** Breadth-first, so the list reads in the order the browser would have
    discovered it — entry first, then its imports, then theirs. */
export function graph(entry = ENTRY) {
  const seen = new Set([entry]);
  const order = [entry];
  for (let i = 0; i < order.length; i++) {
    const rel = order[i];
    for (const spec of importsOf(rel)) {
      const next = path.posix.normalize(path.posix.join(path.posix.dirname(rel), spec));
      if (seen.has(next)) continue;
      if (!fs.existsSync(path.join(ROOT, next))) continue;
      seen.add(next); order.push(next);
    }
  }
  return order;
}

export const BEGIN = '<!-- modulepreload:begin — generated by tools/modulepreload.mjs -->';
export const END = '<!-- modulepreload:end -->';

/** The exact block index.html should contain, entry excluded: the <script>
    tag already starts that one, and naming it twice is a wasted hint. */
export function block(indent = '') {
  const mods = graph().slice(1);
  return [BEGIN, ...mods.map((m) => `<link rel="modulepreload" href="./${m}">`), END]
    .map((l) => indent + l).join('\n');
}

if (process.argv[1] && process.argv[1].endsWith('modulepreload.mjs')) {
  const file = path.join(ROOT, 'index.html');
  const html = fs.readFileSync(file, 'utf8');
  const next = block();
  if (html.includes(BEGIN) && html.includes(END)) {
    const out = html.replace(new RegExp(`${BEGIN}[\\s\\S]*?${END}`), next);
    fs.writeFileSync(file, out);
    console.log(`updated ${graph().length - 1} modulepreload hints`);
  } else {
    console.log(next);
    console.error('\n// markers not found in index.html — printed above, not written');
    process.exit(2);
  }
}
